- name: Insure able to fetch project list
  shell: "oc get projects"
  register: projects_list
  until: projects_list.stdout.find("default") != -1
  retries: 20
  delay: 30

- name: Get latest RSCT Operator version
  shell: |
    curl -s "https://api.github.com/repos/ocp-power-automation/rsct-operator/releases" | grep '"tag_name":' | head -1 | sed -E 's/.*"([^"]+)".*/\1/'
  register: rsct_version
  changed_when: false

- name: Deploy RSCT Operator
  shell: |
    oc create -k "https://github.com/ocp-power-automation/rsct-operator/config/default/?ref={{ rsct_version.stdout }}"
  register: deploy_operator
  failed_when: deploy_operator.rc != 0 and 'AlreadyExists' not in deploy_operator.stderr
  changed_when: deploy_operator.rc == 0

- name: Create RSCT resource
  shell: |
    oc create -k "https://github.com/ocp-power-automation/rsct-operator/config/samples/?ref={{ rsct_version.stdout }}" -n rsct-operator-system
  register: create_rsct_resource
  failed_when: create_rsct_resource.rc != 0 and 'AlreadyExists' not in create_rsct_resource.stderr
  changed_when: create_rsct_resource.rc == 0
