---
# defaults file

workdir: ~/ocp4-workdir
rhcos_kernel_options: []
sysctl_tuned_options: false
powervm_rmc: false  # DEPRECATED: Use powervm_rsct instead. This flag will be removed in a future release.
powervm_rsct: true
node_labels: {}
