---
# Update dhcpd config to not deny unknown clients and use only static entries
- name: Find DHCP pool block
  shell: grep 'pool {' /etc/dhcp/dhcpd.conf
  ignore_errors: yes
  register: dhcp_pool
  when: ansible_distribution_major_version | int < 10

- name: Find DHCP pool block for RHEL 10 and above
  shell: jq -e '.Dhcp4.subnet4[].pools | length > 0' /etc/kea/kea-dhcp4.conf
  ignore_errors: yes
  register: dhcp_pool_rhel10
  when: ansible_distribution_major_version | int >= 10

- name: Update DHCP server config
  when: 
    - ansible_distribution_major_version | int < 10
    - dhcp_pool.rc == 0
  block:
  - name: Remove pool, range and deny statements
    shell: |
      sudo sed -i.bak '/pool {/d' /etc/dhcp/dhcpd.conf
      sudo sed -i '/range /d' /etc/dhcp/dhcpd.conf
      sudo sed -i '$d' /etc/dhcp/dhcpd.conf
      sudo sed -i 's/deny unknown-clients/#deny unknown-clients/' /etc/dhcp/dhcpd.conf
      sudo sed -i 's/authoritative;/#authoritative;/' /etc/dhcp/dhcpd.conf


- name: Update DHCP server config for RHEL 10 and above
  when: 
    - ansible_distribution_major_version | int >= 10
    - dhcp_pool_rhel10.rc == 0
  block:
  - name: Remove pool, range and deny statements
    shell: |
      sudo jq ' .Dhcp4.authoritative = false | .Dhcp4.subnet4[].pools = [] ' /etc/kea/kea-dhcp4.conf | sudo tee /etc/kea/kea-dhcp4.conf.tmp >/dev/null
      sudo mv /etc/kea/kea-dhcp4.conf.tmp /etc/kea/kea-dhcp4.conf

- name: restart dhcpd
  become: true
  service:
    name: dhcpd
    state: restarted
    enabled: yes
  when: ansible_distribution_major_version | int < 10

- name: restart kea-dhcp4 
  become: true
  service:
    name: kea-dhcp4
    state: restarted
    enabled: yes
  when: ansible_distribution_major_version | int >= 10
